### ISSUE TITLE
install 失败。run server 失败

### ISSUE THREAD

**Issue by lunasaw** [444136347/zlm-video-admin#2]
`npm WARN tar ENOENT: no such file or directory, lstat '/Users/weidian/project/luna/zlm-video-admin/node_modules/.staging/@videojs/vhs-utils-138ed859/test/fixtures'
npm WARN tar ENOENT: no such file or directory, lstat '/Users/weidian/project/luna/zlm-video-admin/node_modules/.staging/@videojs/vhs-utils-138ed859/test/fixtures'
npm WARN tar ENOENT: no such file or directory, lstat '/Users/weidian/project/luna/zlm-video-admin/node_modules/.staging/@videojs/vhs-utils-138ed859/test/fixtures'
npm WARN tar ENOENT: no such file or directory, lstat '/Users/weidian/project/luna/zlm-video-admin/node_modules/.staging/@videojs/vhs-utils-138ed859/test/fixtures'
npm WARN tar ENOENT: no such file or directory, lstat '/Users/weidian/project/luna/zlm-video-admin/node_modules/.staging/@videojs/vhs-utils-138ed859/test/fixtures'
npm ERR! code EINTEGRITY
npm ERR! Verification failed while extracting glob@10.4.3:
npm ERR! Verification failed while extracting glob@10.4.3:
npm ERR! sha512-Q38SGlYRpVtDBPSWEylRyctn7uDeTp4NQERTLiCT1FqA9JXPYWqAVmQU6qh4r/zMM5ehxTcbaO8EjhWnvEhmyg== integrity checksum failed when using sha512: wanted sha512-Q38SGlYRpVtDBPSWEylRyctn7uDeTp4NQERTLiCT1FqA9JXPYWqAVmQU6qh4r/zMM5ehxTcbaO8EjhWnvEhmyg== but got sha512-GwMlUF6PkPo3Gk21UxkCohOv0PLcIXVtKyLlpEI28R/cO/4eNOdmLk3CMW1wROV/WR/EsZOWAfBbBOqYvs88/w==. (71972 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/weidian/.npm/_logs/2024-11-20T11_28_18_787Z-debug.log
(base)  ~/project/luna/zlm-video-admin/ [master*] npm run serve

> zlm-video-admin@0.1.0 serve /Users/weidian/project/luna/zlm-video-admin
> vue-cli-service serve

sh: vue-cli-service: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! zlm-video-admin@0.1.0 serve: `vue-cli-service serve`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the zlm-video-admin@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:`

**Comment by 444136347** [comment]
试试清理缓存并重新安装依赖：
1、npm cache clean --force
2、rm -rf node_modules package-lock.json
3、npm install
